# Generated by Django 3.2.9 on 2021-11-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbooking',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='userbooking',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
